### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by miaotony** [miaotony/NUAA_ClassSchedule#16]
- [x] 登录新教务管理系统  Login to the new Educational Administration System   
- [x] 获取课表  Get class schedule data   
- [x] 解析课表  Parse class schedule data  
- [x] 导出课表到`.txt`文件  Export class schedule data to `.txt` file  
- [x] 命令行参数  Get args from terminal  
- [x] 基于对象重构  Refactor based on object  
- [x] 生成 `.ics` 日历文件 :calendar:  Generate `.ics` file  
- [x] 生成 `.xlsx` 表格文件  Generate `.xlsx` file  
- [x] 打包为可执行程序 Packing  
- [x] 图形化界面  GUI  
- [x] 导出考试安排  Export examination schedule  
- [x] 搭建网络服务，在线导出日历文件  Web service  https://github.com/miaotony/NUAA_iCal_Web  
- [x] 搭建 Telegram Bot 在线导出日历文件  Telegram Bot  @NUAA_iCal_bot  https://t.me/NUAA_iCal_bot  
- [ ] 提供课表订阅服务  Subscribe service  
- [ ] 使用情况分析  Usage analysis  
- [ ] 适配研究生课表  Adapt to postgraduate's class schedule  
- [ ] 适配教师课表  Adapt to teacher's class schedule  
- [ ] etc.

**Comment by miaotony** [comment]
**自动获取开学日期**  
打算通过爬取校历来获得。  

GET  http://aao-eas.nuaa.edu.cn/eams/calendarView.action  
POST  http://aao-eas.nuaa.edu.cn/eams/calendarView!search.action
(post data example: `schoolYear=2019-2020&term=2&viewType=A`)

**Comment by miaotony** [comment]
计划新增周数事件，即持续一周的 `第x周` 事件，方便知道当前所在周。
Add events for week number  

样例：
![图片](https://user-images.githubusercontent.com/41962043/109514390-f238be00-7ae0-11eb-9185-31f2b2dad855.png)
